export * from './Slider'
export * from './SliderSeries'
export * from './Hero'
export * from './GenreMenu'
export * from './Episodes'
export * from './DetailedTab'
export * from './CardComp'
export * from './CatCard'